version: "3"

services:
  db:
    image: postgres:11.4-alpine
    environment:
      - POSTGRES_USER=django_food
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=django_food
    ports:
      - 54323:5432

  redis:
    image: redis:5-alpine
    ports:
      - 6378:6379

  app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db:db
      - redis:redis
    depends_on:
      - db
      - redis
    volumes:
      - ./src:/app/src
    command: bash -c "python src/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8099:8000
    env_file:
      - .env

#  flower:
#    image: mher/flower
#    environment:
#      - CELERY_BROKER_URL=redis://redis:6379/
#      - FLOWER_PORT=8888
#    ports:
#      - 5555:8888
#    depends_on:
#      - celery-worker

#  worker:
#    build: .
#    links:
#      - db:db
#      - redis:redis
#    command: bash -c "cd src/ && celery -A ecom.celery worker -l info --concurrency=4"
#    depends_on:
#      - db
#      - redis
#    volumes:
#      - ./src:/app/src
#    environment:
#      - DB_HOST=db
#      - DB_USER=ecom
#      - DB_PASS=12345
#      - DB_PORT=5432
#      - DB_NAME=ecom
#      - DEBUG=True
#      - SECRET_KEY=m7ai5_&crfg7+u8x^ocvd1ha=mf_jwo)+%!iwk#_(dfl_n6#&!
#      - REDIS_HOST=redis
