# Generated by Django 3.1 on 2020-10-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='hit_score',
            field=models.FloatField(default=0.0),
        ),
    ]
